/** Russian translations. Key = the English source string used in t("…"). Missing keys fall back to English. */
export const RU: Record<string, string> = {
  // navigation & shell
  "Home": "Главная", "Projects": "Проекты", "Ideas": "Идеи", "Generations": "Генерации", "Pricing": "Тарифы",
  "Main": "Главное меню", "Language": "Язык", "Profile": "Профиль", "Sign in": "Войти", "Sign out": "Выйти",
  "generations": "генераций", "Generations remaining": "Осталось генераций", "Close": "Закрыть", "Cancel": "Отмена",
  "Back": "Назад", "Retry": "Повторить", "Save": "Сохранить", "Saved": "Сохранено", "Change": "Изменить", "Delete": "Удалить",
  "Open": "Открыть", "Rename": "Переименовать", "Account": "Аккаунт", "Settings": "Настройки", "Just now": "Только что",
  "{n} min ago": "{n} мин назад", "{n} h ago": "{n} ч назад", "Please wait…": "Подождите…",

  // home
  "Idea": "Идея", "Startup": "Стартап", "What do you want": "Что вы хотите", "to build?": "создать?",
  "Describe your idea. AI writes the blueprint, builds a landing page with a waitlist and publishes it on a link.":
    "Опишите идею. ИИ составит план стартапа, соберёт сайт с листом ожидания и опубликует его по ссылке.",
  "Describe your": "Опишите", "Describe your idea": "Опишите вашу идею", "Build my startup": "Создать стартап",
  "Enter to build · Shift+Enter for a new line": "Enter — создать · Shift+Enter — новая строка",
  "idea": "идею", "design": "дизайн", "business": "бизнес", "startup": "стартап", "product": "продукт", "next big thing": "следующий хит",
  "Describe your idea first, or tap an example": "Сначала опишите идею или выберите пример",
  "A meal planner that cooks from what is in my fridge": "Планировщик меню из продуктов, что есть в холодильнике",
  "Cash-flow tool for freelancers who invoice abroad": "Учёт денежного потока для фрилансеров с зарубежными клиентами",
  "An AI study coach for exam season": "ИИ-тренер для подготовки к экзаменам",
  "No idea yet? Find your next startup": "Нет идеи? Найдите свой следующий стартап",
  "Continue building": "Продолжить работу",
  "Choose AI model": "Выбор модели ИИ", "Close model menu": "Закрыть список моделей",
  "Fast and balanced": "Быстрая и сбалансированная", "Fast · great for building": "Быстрая · отлична для создания",
  "Advanced reasoning · paid plans": "Глубокие рассуждения · платные тарифы",

  // build & result
  "Understanding your idea": "Разбираем вашу идею", "Reading intent, audience and constraints": "Цель, аудитория и ограничения",
  "Defining the problem": "Формулируем проблему", "Framing who is hurting, and how much": "Кому больно и насколько",
  "Researching the opportunity": "Изучаем возможность", "Mapping alternatives and demand signals": "Аналоги и признаки спроса",
  "Creating the product blueprint": "Создаём план продукта", "Scoping features and the first release": "Функции и первый релиз",
  "Designing the experience": "Продумываем опыт", "Choosing brand, layout and flows": "Бренд, структура и сценарии",
  "Writing the plan": "Пишем план", "Features, business model, why now": "Функции, бизнес-модель, почему сейчас",
  "Final check": "Финальная проверка", "Making sure the blueprint is coherent": "Проверяем, что план целостный",
  "Building your startup…": "Создаём ваш стартап…", "{model} is working": "{model} работает", "Live blueprint": "План в реальном времени",
  "waiting for the model…": "ждём ответ модели…", "The build did not finish.": "Не удалось завершить создание.",
  "Name": "Название", "Problem": "Проблема", "Audience": "Аудитория", "Solution": "Решение", "First features": "Первые функции",
  "Generated with {model} · v{ver}": "Создано в {model} · v{ver}", "Your startup is taking shape.": "Ваш стартап обретает форму.",
  "Open workspace": "Открыть рабочее пространство", "Edit idea": "Изменить идею", "Regenerate": "Пересоздать", "Improve": "Улучшить",
  "Improving…": "Улучшаем…", "Generate another version": "Другая версия",
  "Regenerate, Improve and Another version use one generation each.": "Пересоздание, улучшение и другая версия тратят по одной генерации.",
  "Target audience": "Целевая аудитория", "Core solution": "Суть решения", "Key features": "Ключевые функции",
  "Possible business model": "Возможная бизнес-модель", "Business model": "Бизнес-модель", "Why now": "Почему сейчас",
  "Sharpened positioning and features": "Позиционирование и функции стали точнее",
  "{name} added to your projects": "{name} добавлен в проекты", "Opened {name}": "Открыт проект {name}", "Project deleted": "Проект удалён",

  // projects, generations
  "{n} startups": "Стартапов: {n}", "Your projects": "Ваши проекты", "New startup": "Новый стартап", "All": "Все",
  "Draft": "Черновик", "Building": "В работе", "Live": "Онлайн", "Created {date}": "Создан {date}",
  "No projects yet.": "Проектов пока нет.", "Your first startup starts here.": "Ваш первый стартап начинается здесь.", "Build something": "Создать проект",
  "{n} generations": "Генераций: {n}", "Startups": "Стартапы", "Websites": "Сайты", "Website": "Сайт",
  "Copy": "Текст", "Research": "Исследование", "Other": "Другое", "Delete this entry from history?": "Удалить запись из истории?",
  "No generations here.": "Здесь пока нет генераций.", "Your ideas will appear here.": "Здесь появятся ваши идеи и проекты.", "Generate an idea": "Сгенерировать идею",

  // ideas
  "Founder tool": "Инструмент основателя", "Find your next startup.": "Найдите свой следующий стартап.", "Let AI discover opportunities worth building.": "ИИ найдёт возможности, которые стоит реализовать.",
  "Industry": "Отрасль", "Difficulty": "Сложность", "Market type": "Тип рынка", "Interests": "Интересы",
  "Fintech": "Финтех", "Health": "Здоровье", "Education": "Образование", "Creator economy": "Экономика авторов", "Climate": "Климат", "Dev tools": "Инструменты разработчика",
  "Indie hackers": "Инди-разработчики", "Students": "Студенты", "Small business": "Малый бизнес", "Creators": "Авторы", "Enterprise": "Крупный бизнес",
  "SaaS": "SaaS", "Marketplace": "Маркетплейс", "Subscription": "Подписка", "Usage-based": "Оплата по использованию",
  "Easy": "Лёгкая", "Medium": "Средняя", "Hard": "Сложная", "Low": "Низкая", "High": "Высокая",
  "AI agents": "ИИ-агенты", "Automation": "Автоматизация", "Remote work": "Удалённая работа", "Wellness": "Благополучие", "Open data": "Открытые данные",
  "Generate ideas": "Сгенерировать идеи", "Uses 1 generation · {n} left": "Тратит 1 генерацию · осталось {n}",
  "Set your filters, then generate.": "Выберите фильтры и запустите генерацию.",
  "STAIRTAP scans the opportunity space and returns startups worth building, with the reasoning attached.": "STAIRTAP изучает рынок и предлагает стартапы, которые стоит создавать, с обоснованием.",
  "Researching the opportunity space…": "Изучаем рынок…", "{n} opportunities": "Возможностей: {n}",
  "Monetization": "Монетизация", "Estimated complexity": "Оценка сложности", "Build this": "Создать это", "Collapse": "Свернуть", "Explore": "Подробнее",

  // pricing & payments
  "Plans": "Тарифы", "More intelligence.": "Больше интеллекта.", "More creation power.": "Больше возможностей для создания.",
  "Every plan turns one idea into a startup. Higher plans give you more generations and the stronger model.": "Любой тариф превращает идею в стартап. Старшие тарифы дают больше генераций и более сильную модель.",
  "Billing period": "Период оплаты", "Monthly": "Ежемесячно", "Yearly · save 20%": "Раз в год · скидка 20%", "Currency": "Валюта",
  "For exploring STAIRTAP.": "Чтобы познакомиться со STAIRTAP.", "For serious builders.": "Для серьёзных создателей.", "For ambitious builders.": "Для амбициозных создателей.",
  "{n} generations per month": "Генераций в месяц: {n}", "{n} assistant messages per day": "Сообщений ассистенту в день: {n}", "Up to {n} projects": "Проектов: до {n}",
  "Gemini Flash model": "Быстрая модель Gemini Flash", "Landing page with a working waitlist": "Лендинг с рабочим листом ожидания", "Publish on a public link": "Публикация по ссылке",
  "Gemini Pro for deeper reasoning": "Gemini Pro для глубоких рассуждений", "Everything in Free": "Всё из бесплатного тарифа", "Everything in Pro": "Всё из тарифа Pro",
  "Recommended": "Рекомендуем", "forever": "навсегда", "/ month": "/ мес.", "Current plan": "Текущий тариф", "Included for everyone": "Доступно всем",
  "Active until {date}.": "Действует до {date}.", "Manage subscription": "Управлять подпиской", "Extend": "Продлить", "Upgrade to {name}": "Перейти на {name}",
  "Founder": "Founder", "Thank you! Activating your purchase…": "Спасибо! Активируем покупку…",
  "Subscriptions paid with crypto do not renew automatically. Pay again to extend.": "Подписка, оплаченная криптой, не продлевается сама. Оплатите ещё раз, чтобы продлить.",
  "Prices in rubles are approximate (1 $ ≈ {rate} ₽). You are always charged in US dollars.": "Цены в рублях приблизительные (1 $ ≈ {rate} ₽). Списание всегда в долларах США.",
  "Prices are in US dollars. Taxes are handled at checkout.": "Цены в долларах США. Налоги учитываются при оплате.",
  "Card payments are processed by Lemon Squeezy, our merchant of record.": "Оплату картой обрабатывает Lemon Squeezy.",
  "Crypto payments (USDT, BTC, ETH and more) are processed by NOWPayments.": "Оплату криптовалютой (USDT, BTC, ETH и др.) обрабатывает NOWPayments.",
  "Payment": "Оплата", "Order": "Заказ", "per month": "в месяц", "per year": "в год", "+{n} generations": "+{n} генераций",
  "≈ {rub} ₽. You are charged in US dollars.": "≈ {rub} ₽. Списание в долларах США.", "Pay by card": "Оплатить картой",
  "Pay with crypto (USDT and others)": "Оплатить криптой (USDT и др.)", "Opening checkout…": "Открываем страницу оплаты…",
  "Payments are not connected yet. Please try again later.": "Приём платежей пока не подключён. Попробуйте позже.",
  "This payment method is not available yet.": "Этот способ оплаты пока недоступен.",
  "Cards issued in Russia are usually not accepted by the card processor. Use crypto in that case.": "Карты российских банков обычно не принимаются платёжным сервисом. В этом случае оплатите криптой.",
  "Crypto pays for one period; there is no automatic renewal. Card plans renew automatically and can be cancelled any time.": "Крипто оплачивает один период, автопродления нет. Карточные подписки продлеваются автоматически и отменяются в любой момент.",
  "Upgrade": "Тариф", "Unlock the full STAIRTAP": "Откройте весь STAIRTAP",
  "More generations, Gemini Pro and more projects for serious founders.": "Больше генераций, Gemini Pro и больше проектов для серьёзных основателей.",
  "Up to 1000 generations every month": "До 1000 генераций каждый месяц",
  "Up to 200 projects and more assistant messages": "До 200 проектов и больше сообщений ассистенту",
  "See plans": "Смотреть тарифы", "Maybe later": "Позже", "More generations": "Больше генераций", "More projects": "Больше проектов",
  "of {n}": "из {n}", "The monthly allowance resets on the 1st. Purchased generations never expire.": "Месячный лимит обновляется 1-го числа. Купленные генерации не сгорают.",
  "Plan active until {date}.": "Тариф действует до {date}.", "Used this month": "Потрачено в этом месяце", "Buy more": "Докупить", "Upgrade plan": "Сменить тариф",

  // login
  "Welcome back": "С возвращением", "Create your account": "Создайте аккаунт", "Sign in to STAIRTAP": "Вход в STAIRTAP", "Start building with AI": "Создавайте с ИИ",
  "Your projects and generations are waiting.": "Ваши проекты и генерации ждут вас.", "Free plan: 10 generations a month. No card needed.": "Бесплатно: 10 генераций в месяц. Карта не нужна.",
  "Password": "Пароль", "Create account": "Создать аккаунт", "No account yet? Create one": "Нет аккаунта? Создайте", "Already have an account? Sign in": "Уже есть аккаунт? Войдите",
  "Wrong email or password.": "Неверная почта или пароль.", "This email is already registered. Sign in instead.": "Эта почта уже зарегистрирована. Войдите.",
  "Enter a valid email address.": "Введите корректный адрес почты.", "Use a password of at least 8 characters.": "Пароль должен быть не короче 8 символов.",
  "Too many attempts. Wait a few minutes and retry.": "Слишком много попыток. Подождите несколько минут.",

  // errors
  "You are out of generations. Upgrade or buy more.": "Генерации закончились. Смените тариф или докупите.",
  "Gemini Pro is available on paid plans.": "Gemini Pro доступен на платных тарифах.", "Project limit reached for your plan.": "Достигнут лимит проектов вашего тарифа.",
  "Daily message limit reached. Try again tomorrow or upgrade.": "Дневной лимит сообщений исчерпан. Попробуйте завтра или смените тариф.",
  "The AI is busy right now. Try again in a minute.": "ИИ сейчас перегружен. Повторите через минуту.",
  "The AI service is not available from the server's region. Contact support.": "ИИ-сервис недоступен из региона сервера. Обратитесь в поддержку.",
  "AI is not configured yet. Contact support.": "ИИ ещё не настроен. Обратитесь в поддержку.",
  "The AI service rejected the request. Contact support.": "ИИ-сервис отклонил запрос. Обратитесь в поддержку.",
  "The AI service did not answer. Nothing was charged. Try again.": "ИИ-сервис не ответил. Генерация не списана. Повторите.",
  "The AI returned an unusable answer. Nothing was charged. Try again.": "ИИ вернул непригодный ответ. Генерация не списана. Повторите.",
  "The AI returned an empty answer. Nothing was charged. Try again.": "ИИ вернул пустой ответ. Генерация не списана. Повторите.",
  "No connection to the server. Check your internet and retry.": "Нет связи с сервером. Проверьте интернет и повторите.",
  "Too many attempts. Wait a few minutes.": "Слишком много попыток. Подождите несколько минут.", "Server error. Try again in a moment.": "Ошибка сервера. Повторите чуть позже.",
  "Something went wrong. Try again.": "Что-то пошло не так. Повторите.",

  // settings & profile
  "General": "Общие", "Appearance": "Внешний вид", "AI preferences": "Настройки ИИ", "Security": "Безопасность", "Billing": "Оплата",
  "Display name": "Отображаемое имя", "Shown in the header and on your profile.": "Показывается в шапке и в профиле.", "Used for sign-in.": "Используется для входа.",
  "Interface and the language the AI writes in.": "Язык интерфейса и язык, на котором пишет ИИ.",
  "Reduce motion": "Меньше анимации", "Turns off non-essential animation across the app.": "Отключает необязательную анимацию.",
  "Show generation counter": "Показывать счётчик генераций", "Keep the remaining generations visible in the header.": "Остаток генераций всегда виден в шапке.",
  "Default model": "Модель по умолчанию", "Used for every new build. Gemini Pro needs a paid plan.": "Используется для каждой новой генерации. Gemini Pro требует платный тариф.",
  "Changing it signs out your other devices.": "После смены вы выйдете на остальных устройствах.", "Current password": "Текущий пароль", "New password": "Новый пароль",
  "Password changed": "Пароль изменён", "End the session on this device.": "Завершить сеанс на этом устройстве.",
  "Delete account": "Удалить аккаунт", "Removes your projects, published sites and data.": "Удаляет ваши проекты, опубликованные сайты и данные.",
  "Enter your password to delete the account permanently. All projects and published sites will be removed.": "Введите пароль, чтобы удалить аккаунт навсегда. Все проекты и опубликованные сайты будут удалены.",
  "Plan": "Тариф", "Your current subscription.": "Ваша текущая подписка.", "Change plan": "Сменить тариф", "Remaining this period.": "Осталось в этом периоде.", "{n} remaining": "Осталось: {n}",
  "Generations used": "Использовано генераций", "Generations left": "Осталось генераций", "{name} plan": "Тариф {name}",
  "10 generations a month and the fast model. Upgrade for more generations and Gemini Pro.": "10 генераций в месяц и быстрая модель. Перейдите на платный тариф ради большего числа генераций и Gemini Pro.",
  "Manage plan": "Управление тарифом", "All settings": "Все настройки",

  // workspace
  "Overview": "Обзор", "Blueprint": "План", "Checks": "Проверки", "Analytics": "Аналитика", "AI Assistant": "ИИ-ассистент",
  "Project not found.": "Проект не найден.", "It may have been removed.": "Возможно, он был удалён.", "Back to projects": "К проектам",
  "View live site": "Открыть сайт", "Copy link": "Скопировать ссылку", "Link copied": "Ссылка скопирована", "Publish": "Опубликовать", "Publishing…": "Публикуем…",
  "Unpublish": "Снять с публикации", "Unpublished": "Снято с публикации", "Published. Your site is live.": "Опубликовано. Сайт доступен по ссылке.",
  "Website generated": "Сайт создан", "Delete project": "Удалить проект", "Delete this project, its website and its signups?": "Удалить проект, его сайт и список подписчиков?",
  "Progress": "Прогресс", "Next steps": "Следующие шаги", "Blueprint is ready": "План готов", "Generate the website": "Создать сайт", "All checks pass": "Все проверки пройдены",
  "No website yet.": "Сайта пока нет.",
  "AI will write and design a complete landing page with a working waitlist form, based on your blueprint. It costs 1 generation and takes up to a minute.":
    "ИИ напишет и оформит полноценный лендинг с рабочей формой листа ожидания по вашему плану. Это стоит 1 генерацию и занимает до минуты.",
  "Generate website": "Создать сайт", "{n} left": "осталось {n}", "no generations left": "генерации закончились",
  "Preview": "Предпросмотр", "Desktop": "Компьютер", "Phone": "Телефон", "Preview: the form works once the site is published.": "Предпросмотр: форма заработает после публикации.",
  "Change something": "Что изменить", "What should change?": "Что нужно изменить?", "e.g. make it warmer, add a pricing section, shorter hero": "например: сделать теплее, добавить блок с ценами, короче заголовок",
  "Apply": "Применить", "1 generation": "1 генерация", "Regenerate from scratch": "Создать заново",
  "Your site is live. Visitors can join the waitlist.": "Сайт онлайн. Посетители могут записаться в лист ожидания.",
  "Publishing puts the page on a public link. Signups appear under Analytics.": "Публикация открывает страницу по ссылке. Подписчики появятся в разделе «Аналитика».",
  "Download HTML": "Скачать HTML", "Designing and writing your website…": "Проектируем и пишем ваш сайт…", "This takes 20–60 seconds. Please keep this tab open.": "Это займёт 20–60 секунд. Не закрывайте вкладку.",
  "Nothing to check yet.": "Проверять пока нечего.", "Generate the website first, then these automatic checks run on it.": "Сначала создайте сайт, потом эти проверки запустятся автоматически.",
  "Go to Website": "К сайту", "Automatic checks": "Автоматические проверки", "Passed": "Пройдено", "Failed": "Не пройдено",
  "Ask for a fix under Website → Change something, for example: “fix the failed checks”.": "Попросите исправить в разделе «Сайт» → «Что изменить», например: «исправь непройденные проверки».",
  "Page has a title": "У страницы есть заголовок", "Language is declared": "Указан язык страницы", "Works on phones (viewport)": "Корректно на телефонах (viewport)",
  "Search description is set": "Есть описание для поиска", "Exactly one main heading": "Ровно один главный заголовок", "Waitlist form is present": "Есть форма листа ожидания",
  "No external scripts": "Нет внешних скриптов", "Images have alt text": "У изображений есть alt-текст", "Has main and footer regions": "Есть основная область и подвал", "Page is lightweight": "Страница лёгкая",
  "Analytics start after you publish.": "Аналитика появится после публикации.", "Publish the website and real visits and waitlist signups will appear here.": "Опубликуйте сайт, и здесь появятся реальные визиты и записи в лист ожидания.",
  "Visits, last 7 days": "Визиты за 7 дней", "Total visits": "Всего визитов", "Waitlist signups": "Записей в лист ожидания", "Public link": "Публичная ссылка",
  "Latest signups": "Последние записи", "Export CSV": "Экспорт в CSV", "No signups yet. Share the link.": "Записей пока нет. Поделитесь ссылкой.",
  "I am your {name} co-founder. Ask me to refine the blueprint, write launch copy or plan the next sprint.": "Я ваш сооснователь проекта {name}. Попросите уточнить план, написать текст для запуска или спланировать следующий спринт.",
  "Improve the pricing": "Улучши ценообразование", "Draft a launch post": "Напиши пост о запуске", "Find competitors": "Найди конкурентов",
  "Message the AI assistant": "Сообщение ИИ-ассистенту", "Ask your AI co-founder…": "Спросите своего ИИ-сооснователя…", "Send message": "Отправить",
  "{n} messages left today. Chat does not use generations.": "Сообщений на сегодня: {n}. Чат не тратит генерации.",
  "Legal": "Документы", "Terms, privacy and refunds": "Условия, конфиденциальность и возвраты", "Contact": "Контакты",
  "Terms": "Условия", "Privacy": "Конфиденциальность", "Refunds": "Возвраты",
  "Password reset": "Сброс пароля", "Forgot your password?": "Забыли пароль?", "Enter your email and we will send a link to set a new password.": "Введите почту — мы отправим ссылку для создания нового пароля.",
  "If this email is registered, a reset link is on its way.": "Если эта почта зарегистрирована, ссылка для сброса уже отправлена.", "Send reset link": "Отправить ссылку",
  "Set a new password": "Задайте новый пароль", "This link is invalid or has expired. Request a new one.": "Ссылка недействительна или устарела. Запросите новую.",
};
